---
driver:
  name: dokken
  chef_version: 12
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: chirantanmitra/centos-systemd:v1
      platform: rhel

suites:
  - name: default
    run_list:
      - recipe[chef_example::default]
    attributes:
      chef_example:
        foo: foo-value-override
